### ISSUE TITLE
Certain icons dont render correct color when Single Point Symbol Outline Width is anything greater than 0

### ISSUE THREAD

**Issue by tbarry2** [missioncommand/mil-sym-android#103]
G*MPNEB---****X - Biological
G*MPNEC---****X Chemical 
G*MPNZ----****X Nuclear

These icons should render as yellow. If you use setSinglePointSymbolOutlineWidth(0) they render correctly as yellow. If you use any number greater than 0 they render as white. If you use the MilStdAttributes.LineColor to change the line color to yellow they render as black. MilStdAttributes.FillColor has no effect.

This is using Symbology_2525C

**Comment by tbarry2** [comment]
Happens even if I do not call setSinglePointSymbolOutlineWidth(). It also happens even if I do not use any attributes or modifiers (im passing in empty SparseArray<String> for each).

Calling this:
![Capture](https://github.com/missioncommand/mil-sym-android/assets/8743047/3a85a643-32eb-4d0f-be70-8148c580df98)

Produces this:
![Screenshot_20240311_175553](https://github.com/missioncommand/mil-sym-android/assets/8743047/38ba1439-b41f-441e-b2a6-11f270411542)

**Comment by michael-spinelli** [comment]
Ok, I see what's happening.
The fill is getting drawn before the outline, so when the symbol is small, the outline covers up the fill.
So at small sizes, the fill gets partially covered.

The simplest change I could make, since this project is dead, was to fix a bug where MilStdAttributes.OutlineSymbol was not being respected. Released v0.1.56.
Pass this in for those symbols:
attributes.put(MilStdAttributes.OutlineSymbol,"false");

The filled symbols from appendix B do not need an outline as they are easier to read like regular units.

You can call SymbolUtilties.hasDefaultFill(String symbolID) and it returns true for those 3 symbols you listed above.

You can call SymbolUtilties.isTGSPWithFill(String symbolID) to determine if a symbol is one of those C2 symbols that can have a fill (like Action Points).  This includes the above 3 but the rest you'd have to specify a fill color in order to see a fill.

**Comment by tbarry2** [comment]
Perfect! Thats even better for us because we really only wanted to add the outline for certain symbols that are hard to see on the map but i noticed as well the outline symbol attribute wasn't working. Thank you!

**Comment by tbarry2** [comment]
Just tested and it works now. Thank you

**Comment by michael-spinelli** [comment]
I introduced a bug with that fix, going to make a new release.
respond or give me a thumbs up so I know you saw this.
new release will be 0.1.58
created a bug where single point tactical graphics are always small.

**Comment by michael-spinelli** [comment]
release up on github and maven central
