### ISSUE TITLE
Allow user to specifiy mines displayed within static depiction

### ISSUE THREAD

**Issue by michael-spinelli** [missioncommand/mil-sym-android#65]
This is a feature request.  As far as MilStd and USAS are concerned, mines should be sent separately as their own symbols.  There is no way to pass a static depiction between systems and let those system know which mine types exist inside.  Everyone needs to be aware this could result in symbols looking different between systems.  That said, this has been implemented for minefield, dynamic depiction.  I'm considering doing it for static depiction.

**Comment by michael-spinelli** [comment]
direction just came out that the mines will continue to be sent separately.

**Comment by michaeltk3** [comment]
![image](https://user-images.githubusercontent.com/32075980/30597015-b972fa8e-9d23-11e7-810d-8a2365884e51.png)
When plotting a static depiction symbol, there is a default fill applied. Is the renderer going to be changed to not include any fill so that separate mines may be displayed in their place?
