### ISSUE TITLE
Symbol color issue

### ISSUE THREAD

**Issue by Rikcore** [missioncommand/mil-sym-android#95]
Hello, I have an issue with Tactical Graphics symbol color.

For example: GFMPOB------ (Booby trap) makes green symbol instead of black. (many of others mobility/survivability have the same issue.)

Maybe I miss something when I render my symbol but I don't have this problem with warfighting symbol.

**Comment by michael-spinelli** [comment]
Obstacles are drawn in green.  From 2525C:

5.5.1.1 Standard identity. Standard identity refers to the threat posed by the operational
environment object being represented. A tactical graphic may be black or off-white depending
on display background, or standard identity may be indicated using color and/or text. If color is
used, graphics denoting friend shall be shown in either black or blue. For other standard
identities, colors should be assigned in a manner consistent with the standard identity of the
associated tactical symbol. By default, a graphic denoting hostile standard identity shall be
shown in red. If red is not available the graphic shall be drawn in black with the abbreviation
“ENY” placed on the graphic in at least two places. **In addition, if color is available graphics
indicating obstacles shall be drawn in green**; otherwise, all obstacles shall be shown in black.

**Comment by Rikcore** [comment]
Thanks for the answer,

I miss this part of the MILSTD2525C norm.
I will check how to force change the color with the renderer.

Have a nice day.
